#!/bin/bash

ROOTDIR=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
source $ROOTDIR/venv/bin/activate

[ -f $ROOTDIR/.env ] && source $ROOTDIR/.env

usage() {
    echo "Usage: $(basename $0): [-h] [command and arguments]"
}

psql() {
    /usr/bin/psql -d regatta "$@"
}
export -f psql

if [ "$1" = -h ]; then
    usage
    exit 0
fi

if ! /usr/bin/psql -d regatta -c "select 'Ok'" &>/dev/null; then
    echo "Starting Postgres with sudo. Use <Ctrl-C> to skip."
    sudo pg_ctlcluster 12 main start
fi

if [ "$1" ]; then
    "$@"
else
    bash --rcfile $ROOTDIR/env.bashrc
fi
